CREATE DATABASE IF NOT EXISTS db;
USE db;

CREATE TABLE IF NOT EXISTS Users (
   user_id INT PRIMARY KEY AUTO_INCREMENT,
   username VARCHAR(50) NOT NULL,
   password VARCHAR(255) NOT NULL,
   powerlvl INT NOT NULL
);

CREATE TABLE Posts (
   post_id INT PRIMARY KEY AUTO_INCREMENT,
   user_id INT NOT NULL,
   category VARCHAR(50),
   image_url VARCHAR(255) NOT NULL,
   post_link VARCHAR(255) NOT NULL,
   title VARCHAR(100) NOT NULL,
   description TEXT,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   FOREIGN KEY (user_id) REFERENCES Users(user_id)
);
